### ISSUE TITLE
Allow devdns to be used as a library

### ISSUE THREAD

**Issue by lsmag** [robbiev/devdns#1]
Hi,

I'm building a tool that will use something just like devdns does, but I actually prefer to use this as a library instead of a executable.

Do you have any problem with a pull request that changes your code to be used _both_ as a library and an executable? I'm afraid in this case the api will be broken, but I don't think this could be an issue (people would just need to install it another way).

**Comment by robbiev** [comment]
There's not a lot of code there, I recommend you just copy the code you need into your project - the license allows you to pretty much do whatever you want with it (MIT).
