### ISSUE TITLE
Feature request: resolve to other IP than only 127.0.0.1

### ISSUE THREAD

**Issue by RickWong** [robbiev/devdns#2]
Hi, to make `devdns` incredibly useful for vagrant / virtualbox users, it would be terrific if an alternative IP address could be returned. One that points to the virtual machine.

**Comment by robbiev** [comment]
Great idea, I'll take a look next time I have the chance.

**Comment by robbiev** [comment]
As a workaround you can probably do a port mapping in Vagrant.

**Comment by robbiev** [comment]
Fixed by #3, I will cut a new release.
